### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by cv-lab-x** [Luciferbobo/DetRF#2]
hi, thansk for your great work, there's some error about the render:

`D4NeRF/render_utils.py", line 1250, in batchify_rays_sm
    all_ret = {k: torch.cat(all_ret[k], 0) for k in all_ret}`

i have already change the chunk to from 1024*16 to 128.
Looking for your reply, thanks. @Luciferbobo

**Comment by Luciferbobo** [comment]
It's probably a issue with the device. The default setting for rendering is designed for 24GB NVIDIA RTX 3090. You might want to try lowering both the chunk and net_chunk numbers.

**Comment by Luciferbobo** [comment]
Thx! Sry for the late response, I've been overwhelmed. It's probably an issue with the device. The default setting for rendering is designed for 24GB NVIDIA RTX 3090. You might want to try lowering both the chunk and net_chunk numbers.
