### ISSUE TITLE
Training and inference time.

### ISSUE THREAD

**Issue by JiaHeng-DLUT** [Luciferbobo/DetRF#3]
Awesome work!

Want to know the training and inference time.

**Comment by Luciferbobo** [comment]
Thx. Sry for the late response, I've been overwhelmed. Training a complete model for 5e5 iterations takes roughly 44 hours on four NVIDIA RTX 3090s. Rendering a novel view takes about 8 seconds. (when applied to 510 × 272)

**Comment by Luciferbobo** [comment]
Thx! Sry for the late response, I've been overwhelmed. Training a complete model for 5e5 iterations takes roughly 44 hours on four NVIDIA RTX 3090s. Rendering a novel view takes about 8 seconds. (when applied to 510 × 272)
